@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Human Resources\n Manager" as ADM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorControlller" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant "SkillsRepository:\nSkillsRepository" as SkillsRepository
participant "collaboratorRepository:\ncollaboratorRepository" as collaboratorRepository
participant "collaborator\n:Collaborator" as COLLABORATOR

activate ADM

        ADM -> UI : asks to assign skills to a collaborator

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL

            UI --> ADM : displays list of collaborators and asks to select one
        deactivate UI

    ADM -> UI : selects the collaborator
    activate UI

    UI -> CTRL : getSkillsList()
        activate CTRL

            CTRL -> REP : getInstance()
            activate REP

            REP --> CTRL: repositories
            deactivate REP

            CTRL -> REPS : getSkillsRepository()
            activate REPS

            REPS --> CTRL: SkillsRepository
            deactivate REPS

            CTRL -> SkillsRepository: getSkillsList()
            activate SkillsRepository

            SkillsRepository --> CTRL : SkillsList
            deactivate SkillsRepository

            CTRL --> UI : SkillsList
            deactivate CTRL

        UI --> ADM : displays list of skills
    deactivate UI

    ADM -> UI : selects skills and assign to the collaborator
    activate UI

        UI --> ADM : shows all data and requests confirmation
    deactivate UI

    ADM -> UI : confirms data
    activate UI

        UI -> CTRL: registerCollaborator(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber, jobName)

                activate CTRL

                    CTRL -> CTRL: getJobsByName(jobName)
                    activate CTRL

                    CTRL -> REP: getInstance()
                    activate REP

                    REP --> CTRL: repositories
                    deactivate REP

                    CTRL -> REPS: getJobRepository()
                    activate REPS

                    REPS --> CTRL: jobRepository
                    deactivate REPS

                    CTRL -> jobRepository: getJobsByName(jobName)
                    activate jobRepository

                    jobRepository --> CTRL: job
                    deactivate jobRepository

                    CTRL --> CTRL: job
                    deactivate CTRL

                    CTRL -> REP: getInstance()
                    activate REP

                    REP --> CTRL: repositories
                    deactivate REP

                    CTRL -> REPS: getCollaboratorRepository()
                    activate REPS

                    REPS --> CTRL: collaboratorRepository
                    deactivate REPS

                    CTRL -> collaboratorRepository: registerCollaborator(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber, job)
                    activate collaboratorRepository

                        collaboratorRepository -> COLLABORATOR** : register(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber, job)

                        collaboratorRepository -> collaboratorRepository: addCollaborator (colaborator)
                        activate collaboratorRepository

                        collaboratorRepository -> collaboratorRepository: validateCollaborator (colaborator)
                        activate collaboratorRepository

                        collaboratorRepository --> collaboratorRepository
                        deactivate collaboratorRepository

                        collaboratorRepository --> collaboratorRepository
                        deactivate collaboratorRepository

                    collaboratorRepository --> CTRL: collaborator
                    deactivate collaboratorRepository

                CTRL --> UI: collaborator
                deactivate CTRL
            UI --> ADM: displays operation success
    deactivate UI

deactivate ADM

@enduml