@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Vehicle and Equipment \nFleet Manager" as Employee
participant ":System" as System

activate Employee

    Employee -> System : ...
    activate System

        System --> Employee : ...
    deactivate System

    Employee -> System : ...
    activate System

        System --> Employee : ...
    deactivate System

    Employee -> System : ...
    activate System

        System --> Employee : ...
    deactivate System

    Employee -> System : ...
    activate System

        System --> Employee : ...

@enduml