@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Green Spaces\nManager" as GSM
participant ":System" as System

activate GSM

    GSM -> System : ...
    activate System

        System --> GSM : ...
    deactivate System

    GSM -> System : ...
    activate System

        System --> GSM : ...
    deactivate System

@enduml