@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Organization\nHRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new job
    activate System

        System --> Employee : shows all jobs category existing to date or asks to create one
    deactivate System

    Employee -> System : selects an option
    activate System

        System --> Employee : requests data (i.e. name)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System
@enduml