@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterCollaboratorUI {

}

class RegisterCollaboratorControlller {

}

class CollaboratorRepository {

}

class Collaborator {

}

class JobRepository {

}

class HRM {

}

class Repositories {

}

RegisterCollaboratorUI ..> RegisterCollaboratorControlller
RegisterCollaboratorControlller ..> Repositories
RegisterCollaboratorControlller ..> CollaboratorRepository
CollaboratorRepository --> Collaborator
HRM --> Collaborator
Repositories --> CollaboratorRepository
Repositories --> JobRepository

@enduml