@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterCollaboratorUI {
}

class RegisterCollaboratorController {
    +RegisterCollaboratorController()
    +getJobsList()
    +registerCollaborator(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber)
}

class CollaboratorRepository {
    -addCollaborator(collaborator)
    -validateCollaborator(collaborator)
    +registerCollaborator(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber, job)
}

class Collaborator {
    -String name
    -String birthday
    -String admissionDate
    -String address
    -int phoneNumber
    -String email
    -String idDocType
    -int idNumber
    +Collaborator(name, birthday, admissionDate, address, phoneNumber, email, idDocType, idNumber, job)

}

class JobRepository {
    +getJobsByName()
}

class Job {
    -String name
    +Job(name)
}

class HRM {
    - name
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobRepository()
    + getCollaboratorRepository()
}

RegisterCollaboratorUI ..> RegisterCollaboratorController
RegisterCollaboratorController ..> Repositories: repositories
RegisterCollaboratorController ..> CollaboratorRepository: CollaboratorRepository
RegisterCollaboratorController ..> JobRepository: JobRepository
Repositories --> Repositories: instance
Repositories --> "1" CollaboratorRepository
Repositories --> "1" JobRepository
CollaboratorRepository --> "*" Collaborator
JobRepository --> "*" Job
Collaborator --> "1" Job
HRM --> Collaborator
HRM --> Job

@enduml