@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "HRM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : Access interface
    activate System

        System --> Employee : Shows interface
    deactivate System

    Employee -> System : Add/remove/edit/view/search skills
    activate System

        System --> Employee : Shows all data and requests confirmation for the operation
    deactivate System

    Employee -> System : Confirms data
    activate System

        System --> Employee : Displays operation success
    deactivate System

@enduml