@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterVehicleUI {

}

class RegisterVehicleControlller {

}

class VehicleRepository {

}

class Vehicle {

}

class FM {

}

class Repositories {

}

RegisterVehicleUI ..> RegisterVehicleControlller
RegisterVehicleControlller ..> Repositories
RegisterVehicleControlller ..> VehicleRepository
VehicleRepository --> Vehicle
FM --> Vehicle
Repositories --> VehicleRepository

@enduml