@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class RegisterVehicleUI {

}

class RegisterVehicleControlller {
    +RegisterVehicleController()
    +registerVehicle(brand, model, tare, grossWeight, currentKm, registerDate, acquisitionDate, maintenanceCheckUpFrequency, plateNumber, type)
}

class VehicleRepository {
    -addVehicle(vehicle)
    -validateVehicle(vehicle)
    +registerVehicle(brand, model, tare, grossWeight, currentKm, registerDate, acquisitionDate, maintenanceCheckUpFrequency, plateNumber, type)
}

class Vehicle {
    -String brand
    -String model
    -int tare
    -int grossWeight
    -int currentKm
    -String registerDate
    -String acquisitionDate
    -int maintenanceCheckUpFrequency
    -String idNumber
    +Vehicle(brand, model, tare, grossWeight, currentKm, registerDate, acquisitionDate, maintenanceCheckUpFrequency, plateNumber, type)

}

class FM {
    - name
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

RegisterVehicleUI ..> RegisterVehicleControlller
RegisterVehicleControlller ..> Repositories
RegisterVehicleControlller ..> VehicleRepository
VehicleRepository --> Vehicle
FM --> Vehicle
Repositories --> VehicleRepository

@enduml