@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Fleet\nManager" as FM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleControlller" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "vehicleRepository:\nvehicleRepository" as vehicleRepository
participant "vehicle\n:Vehicle" as VEHICLE

activate FM

        FM -> UI : asks to register a new vehicle

        activate UI

'            UI --> ADM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getTaskCategories()
            activate CTRL

                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getTaskCategoryRepository()
                activate PLAT

                    PLAT --> CTRL: taskCategoryRepository
                deactivate PLAT

                CTRL -> TaskCategoryRepository : getTaskCategories()
                activate TaskCategoryRepository

                    TaskCategoryRepository --> CTRL : taskCategoryList
                deactivate TaskCategoryRepository

                CTRL --> UI : taskCategoryList
            deactivate CTRL

            UI --> FM : requests data
        deactivate UI

    FM -> UI : types/selects requested data
    activate UI

        UI --> FM : shows all data and requests confirmation
    deactivate UI

    FM -> UI : confirms data
    activate UI

        UI --> FM : displays operation success
    deactivate UI

deactivate FM

@enduml