@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

'title Use Case Diagram Example

left to right direction

rectangle "System Actors" as actors {
    actor Freelancer
    actor Collaborator
    actor "Green\nSpaces\nManager" as GSM
    actor "Green\nSpaces\nUser" as GSU
    actor "Human\nResources\nManager" as HRM
    actor "Fleet Manager" as FM
    actor "Organization\nEmployee" as Employee
}

rectangle "Use Cases" as usecases{
    usecase "UC6 - Create a Task" as UC66
    Employee --> UC66
    usecase "UC1 - Register Skills of a Collaborator" as UC1
    HRM --> UC1
    usecase "UC2 - Register a Job" as UC2
    HRM --> UC2
    usecase "UC3 - Register collaborator with job and fundamental characteristics" as UC3
    HRM --> UC3
    usecase "UC4 - ..." as UC4
    HRM --> UC4
    usecase "UC5 - ..." as UC5
    HRM --> UC5
    usecase "UC6 - Register a vehicle" as UC6
    FM --> UC6
    usecase "UC7 - Register Vehicle's Check-up" as UC7
    FM --> UC7
    usecase "UC8 - Create a Task" as UC8
    FM --> UC8
}

@enduml