@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class CheckUpRepository{

}

class VehicleRepository{

}

class VehicleNeedingMaintenanceRepository{

}

class Repositories{

}

class VehicleNeedingMaintenanceController{

}

class VehicleNeedingMaintenanceUI{

}

@enduml