@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as COLLABORATOR
participant ":ConsultTasksUI" as UI
participant ":ConsultTasksController" as CTRL
participant ":Repositories" as REP
participant "repositories\n:Repositories" as REPS
participant "agenda:\nAgenda" as AGENDA
participant ":EntryMapper" as entryMAPPER
participant "entryDto\n:EntryDto" as entryDTO
participant "entryListDto\n:List<entryDto>" as entryListDTO
participant "authenticationRepository:\nAuthenticationRepository" as authentication
participant "authenticationFacade:\nAuthFacade" as authFacade
participant "user:\nUserSession" as user
participant "entryList:\nEntryList" as entryList
participant "entry:\nEntry" as ENTRY
participant "Green Spaces\nManager" as GSM

activate COLLABORATOR

COLLABORATOR -> UI : Requests to consult tasks
activate UI

    UI -> CTRL : create
    activate CTRL

    UI -> CTRL : getTasksForCollaboratorBetweenDates(startDate, endDate)
    activate CTRL

        CTRL -> REP : getInstance()
        activate REP

        REP --> CTRL: repositories
        deactivate REP

        CTRL -> REPS : getAgenda()
        activate REPS

        REPS --> CTRL: agenda
        deactivate REPS

        CTRL -> AGENDA : getTasksForCollaboratorBetweenDates(startDate, endDate)
        activate AGENDA

            AGENDA -> AGENDA : getTasksForCollaboratorBetweenDates(collaboratorEmail, startDate, endDate)
            activate AGENDA

                AGENDA -> ENTRY : getStartingDate()
                activate ENTRY

                ENTRY --> AGENDA : startingDate
                deactivate ENTRY

                AGENDA -> ENTRY : getTeamAssign()
                activate ENTRY

                ENTRY --> AGENDA : teamAssign
                deactivate ENTRY

                AGENDA -> USER : getEmail()
                activate USER

                USER --> AGENDA : collaboratorEmail
                deactivate USER

                AGENDA -> AGENDA : checkDateWithinRange(startingDate, startDate, endDate)
                activate AGENDA

                AGENDA --> AGENDA
                deactivate AGENDA

                AGENDA -> ENTRY : getTeamAssign()
                activate ENTRY

                ENTRY --> AGENDA : teamAssign
                deactivate ENTRY

                AGENDA -> USER : getEmail()
                activate USER

                USER --> AGENDA : collaboratorEmail
                deactivate USER

                AGENDA -> AGENDA : verifyCollaborator(entry, collaboratorEmail)
                activate AGENDA

                    AGENDA -> ENTRY : getTeamAssign()
                    activate ENTRY

                    ENTRY --> AGENDA : teamAssign
                    deactivate ENTRY

                    AGENDA -> USER : getEmail()
                    activate USER

                    USER --> AGENDA : collaboratorEmail
                    deactivate USER

                AGENDA --> AGENDA
                deactivate AGENDA

            AGENDA --> CTRL : tasks
            deactivate AGENDA

        CTRL --> UI : tasks
        deactivate CTRL

    UI --> COLLABORATOR : Shows list of tasks
    deactivate UI

deactivate COLLABORATOR
@enduml
