@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Job {
}

class Skill {
}

class Vehicle {
}

class Collaborator {
}

class FleetManager {
}

class HumanResourcesManager {
}

MusgoSublime "0..*" -- "1" GreenSpace : manage >
MediumSizedPark "0..*" -- "1" GreenSpace : is a >
Garden "0..*" -- "1" GreenSpace : is a >
LargeSizedPark "0..*" -- "1" GreenSpace : is a >
Collaborator "0..*" -- "1" Job : has >
Collaborator "0..*" -- "1" Skill : has >
HumanResourcesManager "1" -- "1" Job : selects  >
HumanResourcesManager "1" -- "1" Skill : selects  >
HumanResourcesManager "1" -- "1" Job : register  >
Job "1" -- "0..*" Collaborator : assigned to >
Skill "1" -- "0..*" Collaborator : assigned to >
HumanResourcesManager "1" -- "0..*" Collaborator : register >
HumanResourcesManager "1" -- "0..*" Skill : register >
HumanResourcesManager "1" -- "1" Team : generates >
FleetManager "1" -- "0..*" Vehicle : register >
FleetManager "1" -- "0..*" Equipment : manages >
FleetManager "1" -- "0..*" Machine : manages >
FleetManager "1" - "0..*" Checkup : register >
Vehicle "1" -- "*" Checkup : owns >

@enduml