@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

class Vehicle{
    ID
    Brand
    Model
    Type
    TareWeight
    GrossWeight
    CurrentKMS
    RegisterDate
    AcquisitionDate
    MaintenanceFrequency
}

class CheckUp {
    CurrentKMS
    ID
    CheckUpDate
}

class Job {
    name
    description
}


class Collaborator {
    name
    email
    position
    phone
}


class Job {
}

class Skill {
    name
    description
    category
}

class Vehicle {
}

class Collaborator {
}

class FM {
    name
    email
    phone
}

class HRM {
   name
   email
   phone
}

'GreenSpace "1" - "0..*" Employee : has >
'GreenSpace "1" - "0..*" Task: owns >
'Employee "1" -- "*" Task : creates >
'Task "*" - "1" Category: catalogedas >
'TechnicalSkill "*" - "1" ActivityArea: regarding an >

'Category "*" - "*" TechnicalSkill :  : requires >
'(Category, TechnicalSkill) . FeatureTS
'
'GreenSpace "1" -left "1" PostalAddress : located At >

@enduml