@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Organization\nHRM {
    number
}

class Job {
    name


}

'class Category {
'    description
'}

class Colaborator {
    name
    birthdate
    admission date
    address
    contact info
    ID doc type
}

'class User {
'    name
'    email
'    password
'}

'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
Organization\nHRM "1" - "0..*" Colaborator : has >
Organization\nHRM "1" - "0..*" Job: creates >
'Task "*" -- "1" Employee: created by >
Colaborator "1" -- "*" Job : select >
'Employee "0..1" -- "1" User: acts as >
'Job "*" - "1" Category: cataloged as >
@enduml