@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class Organization {

}

class Job {
    name
    description

}

'class Category {
'    description
'}

class HRM {
    name
    email
    phone
}

'class User {
'    name
'    email
'    password
'}

'Platform "1" -- "*" Category : defines >
'Organization "1" - "0..*" HRM : has >
Organization "1" - "0..*" Job: has >
Job "1" -- "*" System : has registered >
'Task "*" -- "1" Employee: created by >
HRM "1" -- "*" Job : creates   >
'Employee "0..1" -- "1" User: acts as >
'Job "*" - "1" Category: cataloged as >
@enduml