    @startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class FM {
    name
    email
    phone
}

class Checkup {
    ID
    plate number
     KMS
     date
}

class Vehicle {
    ID
    Brand
    Model
    Type
    Tare
    Gross Weight
    Current Km
    Register Date
    Acquisition Date
    Maintenance
}

FM "1" - "0..*" Checkup : creates >
Vehicle "1" -- "*" Checkup : owns >
Checkup "1" -- "*" System : has registered >

@enduml