@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "JobRepository" as JOBS
participant "job\n:Job" as JOB

autonumber 16
-> JOBS: registerJob(name, description)

autonumber 16.1
activate JOBS
    group Register Job

        JOBS -> JOB**: register(name, description)
        JOBS -> JOBS: addJob (job)

        activate JOBS
            JOBS -> JOBS: validateJob(job)
'
    end

    autonumber 17
    <-- JOBS : job
deactivate JOBS


@enduml