@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


autonumber

'hide footbox

actor "HRM" as HRM
participant ":RegisterJobUI" as UI
participant ":RegisterJobController" as CTRL
participant ":JobRepository" as JOBS
participant "repositories\n:Repositories" as PLAT
participant "job\n:Job" as JOB

activate HRM

        HRM -> UI : asks to create a new job

        activate UI

            create CTRL
            UI -> CTRL** : create

            CTRL -> JOBS : getJobRepository

            JOBS -> CTRL : jobRepository

            UI --> HRM : shows all jobs category existing to date or asks to create one

            HRM --> UI : selects an option

            UI --> HRM : requests data (name, description)

            activate CTRL


    HRM -> UI : types requested data (name, description)
    activate UI


    HRM -> UI : submits data
    activate UI

        UI -> CTRL : registerJob(name,description)
        deactivate UI
        activate CTRL

'            CTRL -> CTRL : getJobCategoryByDescription(taskCategoryDescription)
'            activate CTRL

                CTRL -> PLAT : getInstance()
                activate PLAT

                    PLAT --> CTRL: repositories
                deactivate PLAT

'
            deactivate CTRL


            |||
            CTRL -> JOBS: registerJob(name, description)

                JOBS -> JOB**: registerJob(name, description)

            activate JOBS
            ref over JOBS
                Register Job
            end ref

                HRM --> CTRL : job

            deactivate HRM

            JOBS --> CTRL: job
            deactivate UI

            CTRL --> HRM: job
                        deactivate UI


            UI --> HRM: displays operation success
    deactivate UI

deactivate HRM

@enduml