@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "hrm\n:HRM" as HRM
participant "job\n:Job" as JOB

autonumber 16
-> HRM: createJob(name, description,reference, hrm )

autonumber 16.1
activate HRM
    group Create Job

        HRM -> JOB**: create(name, description,reference, hrm)
        HRM -> HRM: addJob (job)

        activate HRM
            HRM -> HRM: validateTask(task)
            activate HRM
                HRM --> HRM
            deactivate HRM

            HRM --> HRM
        deactivate HRM
    end

    autonumber 17
    <-- HRM : task
deactivate HRM


@enduml