@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class JobList{
    -String reference
}
class HRM {
    - name
    - email
    - position
    - phone
}

class Job {
    - String name
    - String description
    - String reference

    + Job(name, description, reference)
}

'class TaskCategory {
'    - String description
'
'    + TaskCategory(description)
'}

class Organization {
    - String name
    - String vatNumber
    - String website
    - String phone
    - String email

    - addJob(job)
    - validateJob(job)
    + anyHRMHasEmail(email)
    + Organization(name, vatNumber, webSite, phone, email, postalAddress, manager)
    + createJob(reference, description, informalDesccription,\ntechnicalDescription, duration, cost, )
    - getHRMByEmail(email)

'  +saveTask(task)
}

'class TaskCategoryRepository {
'    + getTaskCategoryByDescription(description)
'}

class OrganizationRepository {
    + getOrganizationByHRMEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
'    + getTaskCategoryRepository()
    + getOrganizationRepository()
}

class CreateJobController {
    + CreateJobController(organizationRepository)
'    + getTaskCategories()
    + createJob(userEmail, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, categoryDescription)
'    - getTaskCategoryByDescription(taskCategoryDescription)
    - getHRMFromSession()
}

note right of CreateJobController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data
end note

'note bottom of TaskCategoryRepository
'    - used for displaying
'    the category list
'end note

class CreateJobUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

CreateJobUI .> CreateJobController

CreateJobController .> Repositories : repositories

'Repositories -> "1" TaskCategoryRepository

'CreateTaskController ..> TaskCategory
CreateJobController ..> OrganizationRepository : organizationRepository
'CreateTaskController ..> TaskCategoryRepository : TaskCategoryRepository

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

CreateJobController ..> "1" Organization : organization
CreateJobController ..> ApplicationSession
CreateJobController ..> UserSession
'Task "*" --> "1" TaskCategory : taskCategory
'TaskCategoryRepository "1" --> "*" TaskCategory : taskCategory
'Organization "1" --> "*" Task : tasks
Job --> HRM : createdBy
Job --> JobList : belongs to

HRM --> "*" Organization : belongs to

@enduml