@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":CreateJobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
'participant "jobListRepository:\nTaskCategoryRepository" as TaskCategoryRepository

autonumber 3

 -> CTRL : getJobList()
autonumber 3.1
activate CTRL
    group Get Job  List


            CTRL -> RepositorySingleton : getReference()
            activate RepositorySingleton

                RepositorySingleton --> CTRL: repositories
            deactivate RepositorySingleton

            CTRL -> PLAT : getJobList()
            activate PLAT

                PLAT --> CTRL: jobList
            deactivate PLAT

            CTRL -> JobListRepository : getJobList()
            activate JobListRepository

                JobListRepository --> CTRL : jobList
            deactivate JobListRepository


    end
    autonumber 4
    <-- CTRL  : jobList
deactivate CTRL


@enduml