@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Organization\nEmployee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to insert a new vehicle check-up.
    activate System

        System --> Employee : shows all vehicles already \nentered in the system and asks you to select one
    deactivate System
'
    Employee -> System : selects an existent vehicle
    activate System

        System --> Employee : requests data (i.e. plate number, KMS, date)
    deactivate System

    Employee -> System : types requested data
    activate System


        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System
@enduml