@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class AssignVehiclesUI {
}

class AssignVehiclesController {
    +AssignVehiclesController(agenda, vehicleRepository)
    +assignVehiclesToEntry(agendaIndex, vehiclesPlateNumber)
    -getEntryByIndex(agendaIndex)
    -getVehicleByPlateNumber(vehiclesPlateNumber)
    +getEntriesList()
    +getVehiclesList()
}

class Agenda {
    +getEntryByIndex(agendaIndex)
}

class Entry {
    -Date startingDate
    -AgendaStatus status
    -Task task
    -List<Vehicle> vehiclesAssigned
    +Entry(startingDate, task)
    +assignVehicles(vehiclesAssigned)
}

class VehicleRepository {
    +getVehicleByPlateNumber(vehiclePlateNumber)
}

class Vehicle {
    -String plateNumber
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getAgenda()
    + getVehicleRepository()
}

AssignVehiclesUI ..> AssignVehiclesController
AssignVehiclesController ..> Repositories: repositories
AssignVehiclesController ..> Agenda: agenda
AssignVehiclesController ..> VehicleRepository: vehicleRepository
Repositories --> Repositories: instance
Repositories --> "1" Agenda
Repositories --> "1" VehicleRepository
Agenda --> "*" Entry
VehicleRepository --> "*" Vehicle
Entry --> "*" Vehicle

@enduml