@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

skinparam rectangle{
    BorderColor yellow
}

title Use Case Diagram

left to right direction

rectangle "System Actors" as actors {
    actor Collaborator
    actor "Green\nSpaces\nManager" as GSM
    actor "Green\nSpaces\nUser" as GSU
    actor "Human\nResources\nManager" as HRM
    actor "Fleet Manager" as FM
}

rectangle "Use Cases" as usecases{
    usecase "UC01 - Register Skills of a Collaborator" as UC01
    HRM --> UC01
    UC01 --> Collaborator
    usecase "UC02 - Register a Job" as UC02
    HRM --> UC02
    usecase "UC03 - Register collaborator with job and fundamental characteristics" as UC03
    HRM --> UC03
    UC03 --> Collaborator
    usecase "UC04 - Assign Skills" as UC04
    HRM --> UC04
    UC04 --> Collaborator
    usecase "UC05 - Generate a team proposal automatically " as UC05
    HRM --> UC05
    usecase "UC06 - Register a vehicle" as UC06
    FM --> UC06
    usecase "UC07 - Register Vehicle's Check-up" as UC07
    FM --> UC07
    usecase "UC08 - List the vehicles needing the check-up" as UC08
    FM --> UC08
}

@enduml