@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "FM" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to register a new vehicle's check-up.
    activate System

        System --> Employee : requests data (i.e. plate number, KMS, date)
    deactivate System

    Employee -> System : types requested data
    activate System

        System --> Employee : confirm that there is no longer a plate\n number equal to the one entered and,\n if so, print an error message
    deactivate System

        System --> Employee : shows all data and requests confirmation
    deactivate System

    Employee -> System : confirms data
    activate System

        System --> Employee : displays operation success
    deactivate System

@enduml